[icedos.applications]
defaultEditor = "dev.zed.Zed.desktop"

[icedos.applications.zed]
autosave = false
extensions = []
extraPackages = []
fhs = false
fontSize = 16
formatOnSave = false
vim = false

[icedos.applications.zed.theme]
dark = "One Dark Pro"
light = "One Light"
mode = "system" # Options: 'system', 'dark', 'light'

[icedos.applications.zed.languages]

[icedos.applications.zed.lsp]
