[icedos.applications]
defaultEditor = "codium.desktop"

[icedos.applications.codium.users.username]
autoSave = "off" # Options: 'off', 'afterDelay', 'onFocusChange', 'onWindowChange'
colorTheme = "One Dark Pro Flat"
fontSize = 14
formatOnPaste = true
formatOnSave = true
zoomLevel = 1.5
